import type { LevelConfig } from '@/game/config'

export const sampleLevels: LevelConfig[] = [
  {
    id: 1,
    title: '丢失的文具',
    difficulty: 'easy',
    storyIntro: '课间，同桌张三的铅笔盒不见了，他焦急地在教室里翻找...',
    mission: '帮助张三在教室后走廊找到丢失的文具',
    npcNeeds: '张三',
    postNote: '今天帮张三找到了妈妈送的铅笔，他笑得好开心。原来小小的举手之劳，也能照亮别人的一天。',
    noteDate: '1994-03-15',
    values: '善良',
    helpedPerson: '张三',
    action: '找到丢失的文具',
    location: '教室后走廊',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 2,
    title: '雨天的伞',
    difficulty: 'easy',
    storyIntro: '放学时下起了大雨，李梅忘了带伞，站在教学楼门口发愁...',
    mission: '在迷宫般的教学楼中找到备用伞',
    npcNeeds: '李梅',
    postNote: '下雨天借给李梅一把伞，她第二天还伞时还带了一颗糖。善意就像涟漪，一圈圈荡开。',
    noteDate: '1994-04-02',
    values: '助人为乐',
    helpedPerson: '李梅',
    action: '借出雨伞',
    location: '教学楼大厅',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 3,
    title: '图书馆的难题',
    difficulty: 'easy',
    storyIntro: '王老师在图书馆整理书籍，但书架太高，很多书放不上去...',
    mission: '穿过书架迷宫，帮王老师整理高处的书籍',
    npcNeeds: '王老师',
    postNote: '帮王老师整理了半个图书馆的书，她夸我懂事。虽然胳膊有点酸，但看到整齐的书架，真开心。',
    noteDate: '1994-04-18',
    values: '尊师重道',
    helpedPerson: '王老师',
    action: '整理书籍',
    location: '学校图书馆',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 4,
    title: '操场边的等待',
    difficulty: 'medium',
    storyIntro: '一年级的小明在操场边哭泣，他的皮球滚进了杂物间...',
    mission: '穿越操场迷宫，进入杂物间找回小明的皮球',
    npcNeeds: '小明',
    postNote: '在杂物间找到了小明的皮球，他破涕为笑的样子真可爱。被需要的感觉，真好。',
    noteDate: '1994-05-06',
    values: '关爱幼小',
    helpedPerson: '小明',
    action: '找回皮球',
    location: '学校操场',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 5,
    title: '食堂的热汤',
    difficulty: 'medium',
    storyIntro: '食堂阿姨忙得不可开交，有同学打翻了汤碗...',
    mission: '穿过食堂迷宫，帮阿姨收拾并安慰同学',
    npcNeeds: '食堂阿姨',
    postNote: '帮阿姨收拾了打翻的汤，阿姨说我是好孩子，还多给我盛了一勺红烧肉。温暖是会传递的。',
    noteDate: '1994-05-20',
    values: '勤劳',
    helpedPerson: '食堂阿姨',
    action: '帮忙收拾',
    location: '学校食堂',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 6,
    title: '黑板报比赛',
    difficulty: 'medium',
    storyIntro: '班级黑板报比赛要开始了，文艺委员找不到足够的粉笔...',
    mission: '在走廊迷宫中寻找彩色粉笔',
    npcNeeds: '文艺委员',
    postNote: '跑遍了整条走廊才找到彩色粉笔，但看到我们班得了第一名，一切都值得。',
    noteDate: '1994-06-01',
    values: '集体荣誉',
    helpedPerson: '文艺委员',
    action: '寻找粉笔',
    location: '教学楼走廊',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 7,
    title: '实验课的意外',
    difficulty: 'hard',
    storyIntro: '物理实验课上，同桌不小心打碎了量筒...',
    mission: '穿越实验室迷宫，找到备用量筒',
    npcNeeds: '同桌小华',
    postNote: '帮小华在实验准备室找到了备用量筒，他的手还在抖。我说"没事的，谁都会犯错"。',
    noteDate: '1994-06-15',
    values: '宽容',
    helpedPerson: '小华',
    action: '寻找备用量筒',
    location: '物理实验室',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 8,
    title: '秋天的落叶',
    difficulty: 'hard',
    storyIntro: '秋天到了，校园里落满了树叶，值日生一个人扫不完...',
    mission: '穿过校园迷宫，帮值日生清扫落叶',
    npcNeeds: '值日生',
    postNote: '和金鹏一起扫完了校园的落叶，秋天的阳光透过树枝洒下来，金灿灿的。劳动后的满足感，真好。',
    noteDate: '1994-10-10',
    values: '勤劳',
    helpedPerson: '金鹏',
    action: '清扫落叶',
    location: '校园大道',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 9,
    title: '运动会的水站',
    difficulty: 'hard',
    storyIntro: '运动会上，水站的志愿者中暑了...',
    mission: '穿过运动场迷宫，去水站帮忙',
    npcNeeds: '志愿者同学',
    postNote: '运动会那天热得要命，但我坚持在水站服务了一下午。每个来喝水的同学都说"谢谢"。',
    noteDate: '1994-10-28',
    values: '奉献',
    helpedPerson: '志愿者同学',
    action: '水站服务',
    location: '运动场',
    stars: 2,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
  {
    id: 10,
    title: '最后的铃声',
    difficulty: 'hard',
    storyIntro: '学期最后一天，班主任的教案落在了办公室...',
    mission: '穿过教学楼迷宫，帮班主任取回教案',
    npcNeeds: '班主任',
    postNote: '帮李老师取回了教案，她摸着我的头说"这一年谢谢你"。我突然觉得，这所学校、这些人，已经深深刻在了我的记忆里。',
    noteDate: '1995-01-15',
    values: '感恩',
    helpedPerson: '李老师',
    action: '取回教案',
    location: '教师办公室',
    stars: 3,
    mapData: {
      grid: [],
      playerStart: { x: 1, y: 1 },
      exitPos: { x: 0, y: 0 },
      npcPositions: [],
    },
  },
]
